name: digikam
base: core18

version: '7.0.0-beta3'
adopt-info: digikam

grade: devel
confinement: strict

apps:
  digikam:
    environment:
      DK_PLUGIN_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/digikam"
    command: usr/bin/digikam
    common-id: org.kde.digikam.desktop
    extensions:
    - kde-neon
    plugs:
    - camera
    - home
    - mount-observe
    - network
    - network-bind
    - opengl
    - pulseaudio
    - removable-media
    - udisks2

parts:
  opencv:
    source: https://github.com/opencv/opencv/archive/3.4.9.zip
    source-subdir: opencv-3.4.9
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/
    prime:
      - -include
  digikam:
    after: [opencv]
    source: https://download.kde.org/unstable/digikam/digikam-$SNAPCRAFT_PROJECT_VERSION.tar.xz
    source-checksum: "sha256/97b2f768674afaaca6feb6e661d5c8fc6b88b08f4d4bbab8a6bcc94c19914893"
    plugin: cmake
    stage-packages:
      - libexif12
      - libgphoto2-6
      - libgphoto2-port12
      - libjpeg8
      - libjpeg-turbo8
      - liblensfun1
      - liblqr-1-0
      - libltdl7
      - libtbb2
    build-packages:
      - bison
      - ccache
      - doxygen
      - g++
      - libboost-graph-dev
      - libegl1-mesa-dev
      - libeigen3-dev
      - libexpat1-dev
      - libfl-dev
      - libglib2.0-dev
      - libjpeg-dev
      - liblensfun-dev
      - libmagickcore-dev
      - libpng-dev
      - libsane-dev
      - libsqlite3-dev
      - libtiff-dev
      - libxslt1-dev
      - ninja-build
    build-snaps:
      - kde-frameworks-5-core18-sdk
    build-environment:
      - PATH: "/usr/lib/ccache:$PATH"
    configflags:
      - -GNinja
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - -DBUILD_TESTING=OFF
      - -DDIGIKAMSC_CHECKOUT_PO=OFF
      - -DDIGIKAMSC_CHECKOUT_DOC=OFF
      - -DDIGIKAMSC_COMPILE_PO=OFF
      - -DDIGIKAMSC_COMPILE_DOC=ON
      - -DDIGIKAMSC_COMPILE_DIGIKAM=ON
      - -DENABLE_KFILEMETADATASUPPORT=OFF
      - -DENABLE_AKONADICONTACTSUPPORT=OFF
      - -DENABLE_MYSQLSUPPORT=OFF
      - -DENABLE_INTERNALMYSQL=OFF
      - -DENABLE_MEDIAPLAYER=OFF
      - -DENABLE_LCMS2=ON
      - -DDIGIKAMSC_USE_PRIVATE_KDEGRAPHICS=OFF
      - -DENABLE_DBUS=ON
      - -DENABLE_APPSTYLES=ON
      - -DENABLE_QWEBENGINE=OFF
      - -DOpenCV_DIR=$SNAPCRAFT_STAGE/share/OpenCV
      - -DENABLE_FACESENGINE_DNN=ON
      - -Wno-dev
    parse-info:
      - usr/share/metainfo/org.kde.digikam.appdata.xml
